INSERT INTO PERSON (NAME, LOCATION, BIRTHDAY )
VALUES('Ranga', 'Hyderabad', '1995-08-10');
INSERT INTO PERSON (NAME, LOCATION, BIRTHDAY )
VALUES('James', 'New York', '2001-10-11');
INSERT INTO PERSON (NAME, LOCATION, BIRTHDAY )
VALUES('Pieter', 'Amsterdam', '2003-10-15');
INSERT INTO PERSON (NAME, LOCATION, BIRTHDAY )
VALUES('James', 'Budapest', '1999-10-11');